# Generated by Django 4.2.30 on 2026-08-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(help_text='1부터 시작하는 일차')),
                ('day_case', models.CharField(choices=[('A', '입도일'), ('B', '중간일차'), ('C', '출도일'), ('D', '당일치기')], max_length=1)),
                ('avail_hours', models.FloatField(help_text='constraints.py가 계산한 가용시간')),
                ('target_slots', models.IntegerField(help_text='TargetSlots(d) 계산 결과')),
                ('need_lunch', models.BooleanField(default=False)),
                ('need_dinner', models.BooleanField(default=False)),
                ('need_night_spot', models.BooleanField(default=False)),
                ('override_purpose_main', models.CharField(blank=True, max_length=20)),
                ('override_purpose_sub', models.CharField(blank=True, max_length=20)),
                ('override_priority', models.CharField(blank=True, max_length=20)),
                ('override_region', models.CharField(blank=True, max_length=50)),
                ('lodging', models.ForeignKey(blank=True, help_text='이 날 숙박할 곳 — 코스 완성 후 lodging_matcher가 채움', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.lodging')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='여행 시작 일시 (제주 도착 시각, 집 아님)')),
                ('end_datetime', models.DateTimeField(help_text='여행 종료 일시')),
                ('departure_place_id', models.CharField(blank=True, help_text='출발지 (공항 등). AVAIL_HOURS Case A 계산의 T_start 기준점', max_length=20)),
                ('return_to_departure', models.BooleanField(default=False, help_text='최종 도착지를 출발지로 복귀 설정했는지')),
                ('transport_mode', models.CharField(choices=[('rental_car', '렌터카'), ('own_car', '자가용'), ('taxi', '택시')], max_length=20)),
                ('companion_type', models.CharField(choices=[('alone', '혼자'), ('couple', '연인/배우자'), ('friend', '친구'), ('family_kids', '아이와 가족'), ('parents', '부모님'), ('group', '단체')], max_length=20)),
                ('purpose_main', models.CharField(choices=[('nature', '힐링/자연'), ('food', '식당/카페'), ('photo', '사진/감성'), ('culture', '문화/역사'), ('activity', '체험/액티비티'), ('shopping', '쇼핑/시장')], max_length=20)),
                ('purpose_sub', models.CharField(blank=True, choices=[('nature', '힐링/자연'), ('food', '식당/카페'), ('photo', '사진/감성'), ('culture', '문화/역사'), ('activity', '체험/액티비티'), ('shopping', '쇼핑/시장')], max_length=20)),
                ('course_priority', models.CharField(choices=[('dist', '이동 최소 코스'), ('pref', '취향 중심 코스'), ('relax', '여유로운 코스')], max_length=20)),
                ('region_preference', models.CharField(blank=True, help_text='희망권역', max_length=50)),
                ('mood_tags', models.JSONField(blank=True, default=list, help_text='조용한/활기찬/야경 등 최대 3개')),
                ('include_places', models.JSONField(blank=True, default=list, help_text='가고 싶은 장소 content_id 목록')),
                ('exclude_places', models.JSONField(blank=True, default=list)),
                ('exclude_categories', models.JSONField(blank=True, default=list, help_text="예: ['박물관','액티비티']")),
                ('walk_light', models.BooleanField(default=False, help_text='많이 걷지 않는 코스 선호')),
                ('indoor_outdoor_pref', models.CharField(blank=True, help_text='상관없음/실내중심/야외중심/적절히섞기', max_length=20)),
                ('free_text_input', models.TextField(blank=True, help_text='SBERT 임베딩으로 변환해 Pref 계산에 반영')),
                ('food_pref_1', models.CharField(blank=True, max_length=30)),
                ('food_pref_2', models.CharField(blank=True, max_length=30)),
                ('food_restriction', models.CharField(blank=True, help_text='없음/비건/육류제외/해산물제외/알레르기·기타', max_length=30)),
                ('food_cafe_balance', models.CharField(blank=True, help_text="음식점중심/카페중심/둘다 — purpose_main 또는 sub가 'food'일 때만 유효", max_length=20)),
                ('lodging_capacity', models.IntegerField(blank=True, null=True)),
                ('lodging_type', models.CharField(blank=True, help_text='호텔/리조트·콘도/펜션·민박/게스트하우스/상관없음', max_length=30)),
                ('lodging_conditions', models.JSONField(blank=True, default=list, help_text="예: ['주차가능','취사가능']")),
                ('lodging_budget', models.IntegerField(blank=True, help_text='1박 예산, 참고용', null=True)),
                ('lodging_free_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField(help_text="사용자가 입력한 원문 (예: '카페 하나 더')")),
                ('parsed_delta', models.JSONField(help_text="LLM이 구조화한 결과. 예: {'lock':['성산일출봉'], 'walk_light': true}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_logs', to='trips.triprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='방문 순서 (0부터)')),
                ('slot_type', models.CharField(choices=[('GENERAL', '일반'), ('RESTAURANT', '식당'), ('CAFE', '카페'), ('SNACK', '간식')], default='GENERAL', max_length=20)),
                ('arrive_at', models.DateTimeField()),
                ('depart_at', models.DateTimeField()),
                ('travel_min_from_prev', models.IntegerField(blank=True, help_text='이전 장소로부터의 이동시간 (5분 격자 스냅된 값, routing 엔진 duration_adjusted)', null=True)),
                ('locked', models.BooleanField(default=False, help_text="사용자가 '고정'한 장소인지")),
                ('pref_score', models.FloatField(blank=True, null=True)),
                ('adjusted_qual', models.FloatField(blank=True, null=True)),
                ('cost_move', models.FloatField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.itineraryday')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.triprequest'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('trip', 'day_index')},
        ),
    ]
