# Generated by Django 4.2.30 on 2026-09-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_remove_placestaystat_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
                ('day_case', models.CharField(choices=[('A', '입도일'), ('B', '중간일차'), ('C', '출도일'), ('D', '당일치기')], max_length=1)),
                ('avail_hours', models.FloatField()),
                ('target_slots', models.IntegerField()),
                ('need_lunch', models.BooleanField(default=False)),
                ('need_dinner', models.BooleanField(default=False)),
                ('need_night_spot', models.BooleanField(default=False)),
                ('lodging_options', models.JSONField(blank=True, default=list, help_text='숙박 후보 top3의 content_id 목록. 사용자가 다른 숙소로 바꿀 때 이 중에서 고름')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('departure_place_id', models.CharField(blank=True, max_length=20)),
                ('return_to_departure', models.BooleanField(default=False)),
                ('transport_mode', models.CharField(choices=[('rental_car', '렌터카'), ('own_car', '자가용'), ('taxi', '택시')], max_length=20)),
                ('companion_type', models.CharField(choices=[('alone', '혼자'), ('couple', '연인/배우자'), ('friend', '친구'), ('family_kids', '아이와 가족'), ('parents', '부모님'), ('group', '단체')], max_length=20)),
                ('purpose_main', models.CharField(choices=[('nature', '힐링/자연'), ('food', '식당/카페'), ('photo', '사진/감성'), ('culture', '문화/역사'), ('activity', '체험/액티비티'), ('shopping', '쇼핑/시장')], max_length=20)),
                ('purpose_sub', models.CharField(blank=True, choices=[('nature', '힐링/자연'), ('food', '식당/카페'), ('photo', '사진/감성'), ('culture', '문화/역사'), ('activity', '체험/액티비티'), ('shopping', '쇼핑/시장')], max_length=20)),
                ('region_preference', models.CharField(blank=True, help_text='NE/NW/SE/SW', max_length=2)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('include_places', models.JSONField(blank=True, default=list)),
                ('exclude_places', models.JSONField(blank=True, default=list)),
                ('exclude_categories', models.JSONField(blank=True, default=list)),
                ('walk_light', models.BooleanField(default=False)),
                ('indoor_outdoor_pref', models.CharField(blank=True, max_length=20)),
                ('free_text_input', models.TextField(blank=True)),
                ('food_pref_1', models.CharField(blank=True, max_length=30)),
                ('food_pref_2', models.CharField(blank=True, max_length=30)),
                ('food_restriction', models.CharField(blank=True, max_length=30)),
                ('food_cafe_balance', models.CharField(blank=True, max_length=20)),
                ('lodging_capacity', models.IntegerField(blank=True, null=True)),
                ('lodging_type', models.CharField(blank=True, max_length=30)),
                ('lodging_conditions', models.JSONField(blank=True, default=list)),
                ('lodging_budget', models.IntegerField(blank=True, null=True)),
                ('lodging_free_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dist', '이동 최소 코스'), ('pref', '취향 중심 코스'), ('relax', '여유로운 코스')], max_length=20)),
                ('is_selected', models.BooleanField(default=False, help_text='사용자가 3개 중 최종 선택한 코스인지 (선택 UI 액션으로 갱신)')),
                ('final_score', models.FloatField(blank=True, help_text='course_builder의 Macro 최종점수, 감사용', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='trips.triprequest')),
            ],
            options={
                'unique_together': {('trip', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='ModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField()),
                ('parsed_delta', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_logs', to='trips.recommendedcourse')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('slot_type', models.CharField(choices=[('GENERAL', '일반'), ('RESTAURANT', '식당'), ('CAFE', '카페'), ('SNACK', '간식')], default='GENERAL', max_length=20)),
                ('arrive_at', models.DateTimeField()),
                ('depart_at', models.DateTimeField()),
                ('travel_min_from_prev', models.IntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('hours_uncertain', models.BooleanField(default=False, help_text='영업시간 확인 불가 장소인지 (⚠표시용)')),
                ('pref_score', models.FloatField(blank=True, null=True)),
                ('adjusted_qual', models.FloatField(blank=True, null=True)),
                ('cost_move', models.FloatField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.itineraryday')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.recommendedcourse'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='lodging',
            field=models.ForeignKey(blank=True, help_text='자동 선택된(top1) 숙소. 다음날 출발지로 사용됨', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='places.lodging'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('course', 'day_index')},
        ),
    ]
