# Generated by Django 4.2.30 on 2026-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triprequest',
            old_name='return_to_departure',
            new_name='lodging_need_cooking',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='companion_type',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='departure_place_id',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='exclude_places',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='food_restriction',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='include_places',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='lodging_budget',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='lodging_capacity',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='lodging_conditions',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='mood_tags',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='guests',
            field=models.IntegerField(default=2, help_text='1~20명, 기본 2명 (AI Hub 실측 중앙값)'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='end_datetime',
            field=models.DateTimeField(help_text='복귀편 출발 위해 공항 도착 필요한 시각'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='exclude_categories',
            field=models.JSONField(blank=True, default=list, help_text='TourAPI 중분류 코드 목록 (기획서 2.5 계층형 체크박스, 5개 대분류 하위 중분류)'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='lodging_type',
            field=models.CharField(blank=True, default='상관없음', max_length=30),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='purpose_main',
            field=models.CharField(choices=[('nature', '힐링/자연'), ('food', '음식/카페'), ('photo', '사진/감성'), ('culture', '문화/역사'), ('activity', '체험/액티비티'), ('shopping', '쇼핑/시장')], max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='purpose_sub',
            field=models.CharField(blank=True, choices=[('nature', '힐링/자연'), ('food', '음식/카페'), ('photo', '사진/감성'), ('culture', '문화/역사'), ('activity', '체험/액티비티'), ('shopping', '쇼핑/시장')], max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='region_preference',
            field=models.CharField(choices=[('NE', '북동'), ('NW', '북서'), ('SE', '남동'), ('SW', '남서'), ('ALL', '제주 전역 무관')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='start_datetime',
            field=models.DateTimeField(help_text='입국수속 마친 후 실제 활동 시작 시각 (제주공항 기준)'),
        ),
    ]
