# Generated by Django 4.2.30 on 2026-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rename_return_to_departure_triprequest_lodging_need_cooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='lodging_options_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='추천된 top3 LodgingCard.to_dict() 리스트'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='lodging_snapshot',
            field=models.JSONField(blank=True, help_text='선택된 숙소의 LodgingCard.to_dict() 스냅샷 (별도 테이블 없이 통째 저장)', null=True),
        ),
    ]
