# Generated by Django 4.2.30 on 2026-09-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_itineraryday_lodging_options_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='indoor_outdoor_pref',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='walk_light',
        ),
    ]
