# Generated by Django 4.2.30 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_triprequest_indoor_outdoor_pref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='is_relaxed_preference',
            field=models.BooleanField(default=False, help_text='선호 음식 태그 조건이 완화되어 선택된 항목인지 (문서 §소프트필터-4 투명성)'),
        ),
    ]
