# Generated by Django 4.2.30 on 2026-09-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_itineraryitem_is_relaxed_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='need_morning',
            field=models.BooleanField(default=False),
        ),
    ]
