# Generated by Django 4.2.30 on 2026-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_itineraryday_need_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='day_overrides',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
