# Generated by Django 4.2.30 on 2026-09-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_triprequest_day_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
