# Generated by Django 4.2.30 on 2026-09-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_recommendedcourse_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='avail_start_min',
            field=models.IntegerField(default=540),
        ),
    ]
