# Generated by Django 4.2.30 on 2026-09-13 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_itineraryday_avail_start_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='day_schedules',
            field=models.JSONField(default=list, help_text="[{day_index, start_time:'HH:MM', end_time:'HH:MM', purpose_main?, purpose_sub?, region_preference?, exclude_categories?}, ...]"),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 1), help_text='복귀편 출발 위해 공항 도착 필요한 시각'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triprequest',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 1), help_text='입국수속 마친 후 실제 활동 시작 시각 (제주공항 기준)'),
            preserve_default=False,
        ),
    ]
