# Generated by Django 4.2.30 on 2026-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_remove_triprequest_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='travel_to_next_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
