# Generated by Django 4.2.30 on 2026-09-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_itineraryday_travel_to_next_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='airport_to_first_travel_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
