# Generated by Django 4.2.30 on 2026-09-18 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_itineraryday_airport_to_first_travel_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='guests',
            field=models.IntegerField(default=2, help_text='1~20명, 기본 2명 (AI Hub 실측 중앙값)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
