# Generated by Django 4.2.30 on 2026-09-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_triprequest_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='stay_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
