# Generated by Django 4.2.30 on 2026-09-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0017_lodgingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('NE', '제주시 동부'), ('NW', '제주시 서부'), ('SE', '서귀포 동부'), ('SW', '서귀포 서부'), ('ALL', '제주 전역')], max_length=3)),
                ('region_label', models.CharField(help_text="화면 표시용, 예: '서귀포시 · 성산·표선'", max_length=100)),
                ('duration', models.CharField(default='당일코스', help_text="필터용 코드, 예: '당일코스'", max_length=20)),
                ('badge', models.CharField(help_text="카드 배지, 예: '당일코스 · 9시간'", max_length=50)),
                ('time_of_day', models.JSONField(default=list, help_text="예: ['낮','노을']")),
                ('meta_chips', models.JSONField(default=list, help_text="예: ['☀️ 낮','🌇 노을']")),
                ('gradient', models.CharField(blank=True, help_text='카드 배경 그라데이션 CSS 값', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CuratedCourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curated.curatedcourse')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
