# Generated by Django 4.2.30 on 2026-08-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('content_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('overview', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('small_category_name', models.CharField(blank=True, help_text='호텔/리조트·콘도/펜션·민박/게스트하우스 — 숙박 유형 필터', max_length=50)),
                ('signgu_code', models.CharField(blank=True, max_length=10)),
                ('room_capacity_summary', models.CharField(blank=True, help_text='정확한 숙박 인원 정보. 74.1%만 유효 — 없으면 Unknown 처리 (2.2절 규칙)', max_length=200)),
                ('capacity', models.CharField(blank=True, help_text='전체 수용 인원. 11.8%만 유효 — 사실상 참고용', max_length=50)),
                ('room_type', models.CharField(blank=True, max_length=200)),
                ('room_count', models.CharField(blank=True, max_length=20)),
                ('room_options', models.CharField(blank=True, max_length=300)),
                ('parking', models.CharField(blank=True, help_text='94.8% 유효 — 자동차 이용 시 필터', max_length=20)),
                ('cooking', models.CharField(blank=True, help_text='68.4% 유효 — 취사가능 조건 필터', max_length=20)),
                ('facilities', models.TextField(blank=True, help_text='98.6% 유효 — 부대시설 선호 검색')),
                ('check_in_time', models.CharField(blank=True, max_length=20)),
                ('check_out_time', models.CharField(blank=True, max_length=20)),
                ('min_room_price', models.CharField(blank=True, help_text='51.9%만 유효, 실시간 아님. 참고가로만 노출', max_length=50)),
                ('pickup', models.CharField(blank=True, max_length=20)),
                ('food_place', models.CharField(blank=True, max_length=200)),
                ('pet_allowed_type', models.CharField(blank=True, max_length=100)),
                ('pet_allowed_animals', models.CharField(blank=True, max_length=100)),
                ('pet_requirements', models.CharField(blank=True, max_length=300)),
                ('reservation_info', models.TextField(blank=True)),
                ('reservation_url', models.URLField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('content_id', models.CharField(help_text='TourAPI 고유 ID. 반드시 문자열로 다룰것(앞자리 0손실 방지)', max_length=20, primary_key=True, serialize=False)),
                ('content_type_id', models.CharField(max_length=10)),
                ('content_type_name', models.CharField(db_index=True, help_text='관광지 / 문화시설 / 쇼핑 / 음식점', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('overview', models.TextField(blank=True, help_text='장소 소개글. LLM 목적태깅(DescriptionFit)과 자유입력 임베딩 매칭에 씀')),
                ('homepage', models.URLField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('hours_raw', models.CharField(blank=True, help_text="원문 그대로(예: '11:20~30 (마지막 주문 19:50)). 파싱 실패 시 대조용 남겨둠", max_length=100)),
                ('open_time', models.TimeField(blank=True, help_text='hours_raw를 파싱해서 채우는 필드. import 스크립트가 채움', null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('closed_days_raw', models.CharField(blank=True, max_length=200)),
                ('closed_weekdays', models.JSONField(blank=True, default=list, help_text="파싱된 휴무 요일 배열 (예: ['화']). 하드필터에서 이 필드로 비교")),
                ('fees', models.CharField(blank=True, max_length=500)),
                ('parking', models.CharField(blank=True, help_text="'가능'/'불가능'/'Unknown' — 렌터카 이용 시 하드필터에 사용", max_length=20)),
                ('restroom', models.CharField(blank=True, max_length=50)),
                ('credit_card', models.CharField(blank=True, max_length=20)),
                ('detail_information', models.TextField(blank=True)),
                ('market_days', models.CharField(blank=True, max_length=100)),
                ('sale_items', models.CharField(blank=True, max_length=300)),
                ('featured_menu', models.CharField(blank=True, max_length=300)),
                ('menu', models.TextField(blank=True)),
                ('food_role', models.CharField(blank=True, db_index=True, help_text='음식점 로직 문서 기준 소분류→역할 매핑 결과. RESTAURANT / CAFE / SNACK / BAR 중 하나. import 시 small_category_name으로 계산.', max_length=20)),
                ('region_code', models.CharField(max_length=10)),
                ('signgu_code', models.CharField(help_text='희망권역 필터에 사용', max_length=10)),
                ('large_category_code', models.CharField(max_length=10)),
                ('large_category_name', models.CharField(max_length=50)),
                ('middle_category_code', models.CharField(max_length=10)),
                ('middle_category_name', models.CharField(max_length=50)),
                ('small_category_code', models.CharField(max_length=10)),
                ('small_category_name', models.CharField(help_text='카테고리 중앙값 상속(1순위)의 기준 키. 음식점 food_role 매핑에도 사용', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LodgingEmbedding',
            fields=[
                ('lodging', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.lodging')),
                ('search_text', models.TextField(help_text='title+address+overview+room_type+parking+cooking+food_place+facilities 등 조합')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceEmbedding',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.place')),
                ('search_text', models.TextField(help_text='title + small_category_name + featured_menu + menu + overview 조합 원문')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceStayStat',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stay_stat', serialize=False, to='places.place')),
                ('needs_stay', models.BooleanField(help_text='False면 숙박(체류시간 계산 대상 아님)')),
                ('is_matched', models.BooleanField(help_text='AI Hub 관측이 붙었는지')),
                ('obs_n', models.IntegerField(help_text='OBS_N — 관측 건수')),
                ('n_travel', models.IntegerField(default=0)),
                ('obs_med', models.FloatField(blank=True, null=True)),
                ('w_conf', models.FloatField(help_text='W_CONF = min(OBS_N/3, 1.0)')),
                ('stay_raw', models.FloatField(help_text='격자 올리기 전 원값 (감사용)')),
                ('stay_med_15m', models.IntegerField(help_text='대표값. ItineraryItem 배치 시 StayTime_k로 바로 사용')),
                ('stay_min', models.IntegerField(help_text='밴드 하한 (대표값 아님! 이름 주의)')),
                ('stay_max', models.IntegerField(help_text='밴드 상한')),
                ('stay_src', models.CharField(help_text='observed / blend / category / manual_override / lodging_anchor', max_length=20)),
                ('cat_level', models.CharField(blank=True, max_length=10)),
                ('cat_key', models.CharField(blank=True, max_length=100)),
                ('dgstfn_mean', models.FloatField(blank=True, null=True)),
                ('rcmdtn_mean', models.FloatField(blank=True, null=True)),
                ('qual', models.FloatField(blank=True, help_text='Qual_k (0~1 정규화)', null=True)),
                ('qual_category', models.FloatField(help_text='Qual_category(k) — 카테고리 상속값')),
                ('qual_rel', models.FloatField(help_text='Rel_k — 관측 신뢰도')),
                ('satisfaction_score', models.FloatField(blank=True, help_text='★ = AdjustedQual_k. scoring.py의 Micro 수식에 바로 대입', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTagScore',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.place')),
                ('score_nature', models.IntegerField(help_text='힐링/자연')),
                ('score_food', models.IntegerField(help_text='식당/카페')),
                ('score_photo', models.IntegerField(help_text='사진/감성')),
                ('score_culture', models.IntegerField(help_text='문화/역사')),
                ('score_activity', models.IntegerField(help_text='체험/액티비티')),
                ('score_shopping', models.IntegerField(help_text='쇼핑/시장')),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['signgu_code'], name='places_plac_signgu__6e9fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['content_type_name', 'small_category_name'], name='places_plac_content_7c7d86_idx'),
        ),
        migrations.AddIndex(
            model_name='lodging',
            index=models.Index(fields=['signgu_code'], name='places_lodg_signgu__5f4488_idx'),
        ),
    ]
