# Generated by Django 4.2.30 on 2026-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placestaystat',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placetagscore',
            name='place',
        ),
        migrations.RemoveIndex(
            model_name='lodging',
            name='places_lodg_signgu__5f4488_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_signgu__6e9fbf_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='open_time',
        ),
        migrations.AddField(
            model_name='lodging',
            name='pet_extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lodging',
            name='quadrant',
            field=models.CharField(blank=True, default='SW', max_length=2),
        ),
        migrations.AddField(
            model_name='lodging',
            name='rooms_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lodging',
            name='tripcom_hotel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='food_tags',
            field=models.JSONField(blank=True, default=list, help_text='LLM 다중라벨 10종 (제주향토음식/고기구이/해산물요리/회물회초밥/한식/면요리/분식간편식/일식/중식/양식세계음식). CSV의 콤마구분 문자열을 리스트로 변환해 저장'),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_status',
            field=models.CharField(choices=[('always', '상시영업'), ('windows', '시간대 확정'), ('uncertain', '확인불가')], default='uncertain', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='open_windows',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='place',
            name='quadrant',
            field=models.CharField(choices=[('NE', '북동'), ('NW', '북서'), ('SE', '남동'), ('SW', '남서')], db_index=True, default='SW', max_length=2),
        ),
        migrations.AddField(
            model_name='place',
            name='qual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='qual_category',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='qual_rel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='satisfaction_score',
            field=models.FloatField(blank=True, help_text='★=AdjustedQual_k. Micro 수식에 바로 대입', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='satisfaction_src',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='score_activity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='score_culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='score_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='score_nature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='score_photo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='score_shopping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='stay_max',
            field=models.IntegerField(blank=True, help_text='밴드 상한', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='stay_min',
            field=models.IntegerField(blank=True, help_text='밴드 하한', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='stay_src',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='stay_time_minutes',
            field=models.IntegerField(blank=True, help_text='대표 체류시간(15분격자). CSV의 stay_time_minutes', null=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='cooking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='parking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='room_capacity_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='small_category_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lodgingembedding',
            name='search_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='closed_weekdays',
            field=models.JSONField(blank=True, default=list, help_text="예: ['화']"),
        ),
        migrations.AlterField(
            model_name='place',
            name='content_type_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='food_role',
            field=models.CharField(blank=True, db_index=True, help_text='RESTAURANT/CAFE/SNACK/BAR — small_category_name 기반 import 시 계산', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='hours_raw',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='parking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='placeembedding',
            name='search_text',
            field=models.TextField(help_text='임베딩에 사용된 원문 (title+overview+분류명(+메뉴/food_tags))'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['quadrant'], name='places_plac_quadran_552a69_idx'),
        ),
        migrations.DeleteModel(
            name='PlaceStayStat',
        ),
        migrations.DeleteModel(
            name='PlaceTagScore',
        ),
    ]
