# Generated by Django 4.2.30 on 2026-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_placestaystat_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='large_category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='middle_category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='small_category_name',
            field=models.CharField(help_text='카테고리 중앙값 상속(1순위)의 기준 키. 음식점 food_role 매핑에도 사용', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
