# Generated by Django 4.2.30 on 2026-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_large_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='hours_status',
            field=models.CharField(choices=[('always', '상시영업'), ('windows', '시간대 확정'), ('uncertain', '확인불가')], default='uncertain', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='menu',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='overview',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='parking',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
