# Generated by Django 4.2.30 on 2026-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_hours_status_alter_place_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='credit_card',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='food_role',
            field=models.CharField(blank=True, db_index=True, help_text='RESTAURANT/CAFE/SNACK/BAR — small_category_name 기반 import 시 계산', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='hours_raw',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='place',
            name='stay_src',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
