# Generated by Django 4.2.30 on 2026-09-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_contact_alter_place_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='contact',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='room_capacity_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='small_category_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
