# Generated by Django 4.2.30 on 2026-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_lodging_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='pet_requirements',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='room_capacity_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='room_options',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='room_type',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
