# Generated by Django 4.2.30 on 2026-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_lodging_pet_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='room_options',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
