# Generated by Django 4.2.30 on 2026-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_lodging_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='room_count',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
