# Generated by Django 4.2.30 on 2026-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_lodging_room_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
