# Generated by Django 4.2.30 on 2026-09-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='overview_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
