# Generated by Django 4.2.30 on 2026-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_placeimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_content_id', models.CharField(db_index=True, max_length=30)),
                ('image_url', models.URLField(max_length=1000)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
