# Generated by Django 4.2.30 on 2026-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_lodgingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
