# Generated by Django 4.2.30 on 2026-09-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_place_embedding_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='embedding_vector',
        ),
    ]
