# Generated by Django 4.2.30 on 2026-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_place_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='popularity_score',
            field=models.FloatField(blank=True, help_text='AI_Hub obs_travel_n 기반 인기도 = 1-exp(-0.2*obs_travel_n). 미관측 시 0.0', null=True),
        ),
    ]
