# Generated by Django 4.2.30 on 2026-09-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_place_popularity_score'),
        ('places', '0019_remove_place_embedding_vector'),
    ]

    operations = [
    ]
