# Generated by Django 4.2.30 on 2026-09-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_merge_20260918_1943'),
        ('places', '0020_merge_20260918_1949'),
    ]

    operations = [
    ]
