# Generated by Django 4.2.30 on 2026-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_merge_20260918_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_night_spot',
            field=models.BooleanField(default=False, help_text='AI_Hub 실측 야간 명소(20시 이후 도착 비율). scripts/merge_night_spot_into_places_csv.py가 CSV에 채움'),
        ),
    ]
