# Generated by Django 4.2.30 on 2026-09-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_merge_20260918_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='breakfast_suitable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
