# Generated by Django 4.2.30 on 2026-09-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_place_breakfast_suitable'),
        ('places', '0022_place_is_night_spot'),
    ]

    operations = [
    ]
